/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-11-03 00:58:19
 */


#include <BCDS_Basics.h>
#include <BCDS_Retcode.h>
#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <BCDS_LightSensor.h>
#include <BCDS_Environmental.h>
#include <XdkSensorHandle.h>
#include <BCDS_Gyroscope.h>
#include <stdint.h>
#include <bma2x2.h>
#include <stdbool.h>
#include "ConnectivityHttpRestClientServer.h"
#include "SensorLight.h"
#include "SensorEnvironment.h"
#include "SensorGyroscope.h"
#include "SensorAccelerometer.h"
#include "MitaExceptions.h"
#include "application.h"

#ifndef BCDS_MODULE_ID
#define BCDS_MODULE_ID 0xCAFE
#endif

double tempCorrection = 6.5975f;

Retcode_T initGlobalVariables_application() {
	Retcode_T exception = RETCODE_OK;
	
	if(exception != NO_EXCEPTION) return exception;
	
	return exception;
}

Retcode_T HandleEvery5Second1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	struct bma2x2_accel_data sensorAccelerometerModalityPreparation_1;
	exception = SensorAccelerometer_ReadXYZ(&sensorAccelerometerModalityPreparation_1);
	if(exception != NO_EXCEPTION) return exception;
	
	int32_t accx;
	accx = sensorAccelerometerModalityPreparation_1.x;
	int32_t accy;
	accy = sensorAccelerometerModalityPreparation_1.y;
	int32_t accz;
	accz = sensorAccelerometerModalityPreparation_1.z;
	CalibratedGyro_XyzDpsData_T sensorGyroscopeModalityPreparation_2;
	exception = CalibratedGyro_readXyzDpsValue(&sensorGyroscopeModalityPreparation_2);
	if(exception != NO_EXCEPTION) return exception;
	
	int32_t gyx;
	gyx = sensorGyroscopeModalityPreparation_2.xAxisData;
	int32_t gyy;
	gyy = sensorGyroscopeModalityPreparation_2.yAxisData;
	int32_t gyz;
	gyz = sensorGyroscopeModalityPreparation_2.zAxisData;
	Environmental_Data_T sensorEnvironmentModalityPreparation_3;
	exception = Environmental_readData(xdkEnvironmental_BME280_Handle, &sensorEnvironmentModalityPreparation_3);
	if(exception != NO_EXCEPTION) return exception;
	
	uint32_t humi;
	humi = sensorEnvironmentModalityPreparation_3.humidity;
	double pres = sensorEnvironmentModalityPreparation_3.pressure / 1000.0f;
	double temp = sensorEnvironmentModalityPreparation_3.temperature / 1000.0f;
	temp = temp - tempCorrection;
	uint32_t sensorLightModalityPreparation_4;
	exception = LightSensor_readLuxData(xdkLightSensor_MAX44009_Handle, &sensorLightModalityPreparation_4);
	if(exception != NO_EXCEPTION) return exception;
	
	double light = sensorLightModalityPreparation_4 / 1000.0f;
	char json_buf[324] = {0};
	char *json = json_buf;
	
	char mainHandleEvery5Second12Json_12_buf[324] = {0};
	snprintf(mainHandleEvery5Second12Json_12_buf, sizeof(mainHandleEvery5Second12Json_12_buf), "{\n    \"iid\":\"2611\",\n    \"iaccx\":%" PRId32 ", \n    \"iaccy\":%" PRId32 ", \n    \"iaccz\":%" PRId32 ", \n    \"igx\":%" PRId32 ", \n    \"igy\":%" PRId32 ", \n    \"igz\":%" PRId32 ", \n    \"ilembab\":%" PRIu32 ", \n    \"ipress\":%.6g, \n    \"isuhu\":%.6g, \n    \"ilux\":%.6g\n    }", accx, accy, accz, gyx, gyy, gyz, humi, pres, temp, light);
	memcpy(json, mainHandleEvery5Second12Json_12_buf, sizeof(mainHandleEvery5Second12Json_12_buf));
	
	printf("%s\n", json);
	char* _newConnectivityHttpRestClientServer_Root_1 = json;
	exception = ConnectivityHttpRestClientServer_Root_Write(&_newConnectivityHttpRestClientServer_Root_1);
	if(exception != NO_EXCEPTION) return exception;


	return NO_EXCEPTION;
}


