/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-11-03 00:58:19
 */


#ifndef CONNECTIVITYHTTPRESTCLIENT_HTTPRESTCLIENT_H
#define CONNECTIVITYHTTPRESTCLIENT_HTTPRESTCLIENT_H

#include <BCDS_Retcode.h>


/**
 * Sets up the HttpRestClient.
 */
Retcode_T ConnectivityHttpRestClientServer_Setup(void);

/**
 * Enables the HttpRestClient sensor.
 */
Retcode_T ConnectivityHttpRestClientServer_Enable(void);

/**
 * Provides read access to root.
 */
Retcode_T ConnectivityHttpRestClientServer_Root_Read(char** result);

/**
 * Provides write access to root.
 */
Retcode_T ConnectivityHttpRestClientServer_Root_Write(char** result);


#endif
