/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-11-03 00:58:19
 */


#include <FreeRTOS.h>
#include <BCDS_Basics.h>
#include <BCDS_CmdProcessor.h>
#include <timers.h>
#include <BCDS_Retcode.h>
#include "MitaTime.h"
#include "MitaExceptions.h"
#include "MitaEvents.h"

static TimerHandle_t timerHandleEvery5Second1;

static void InternalHandleEvery5Second1(TimerHandle_t xTimer)
{
	BCDS_UNUSED(xTimer);
	CmdProcessor_Enqueue(&Mita_EventQueue, HandleEvery5Second1, NULL, 0);
}


Retcode_T SetupTime(void)
{
	
	timerHandleEvery5Second1 = xTimerCreate("timerHandleEvery5Second1", UINT32_C(5000), pdTRUE, NULL, InternalHandleEvery5Second1);
	
	if(timerHandleEvery5Second1 == NULL)
	{
		return RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES);
	}
	
	return NO_EXCEPTION;
}

Retcode_T EnableTime(void)
{
	Retcode_T result = NO_EXCEPTION;

	
	result = EveryHandleEvery5Second1_Enable();
	if(result != NO_EXCEPTION)
	{
		return result;
	}
	
	return NO_EXCEPTION;
}

Retcode_T EveryHandleEvery5Second1_Enable(void)
{
	xTimerStart(timerHandleEvery5Second1, 0);
	
	return NO_EXCEPTION;
}


